spring:
  application:
    name: DKGlassDesigns
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: dkglassdesigns
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false